/**
 * anatomy-data.js — ANATOMY module (pilot region: Upper Limb)
 * Text-based study content, written from scratch based on standard
 * musculoskeletal-anatomy knowledge (not copied from any textbook).
 *
 * Structure mirrors a standard PT anatomy curriculum: Bones → Joints → Muscles
 * (grouped, each with Origin / Insertion / Action / Nerve Supply) →
 * 30-question MCQ self-test per region.
 */
'use strict';

const ANATOMY_REGIONS = [
  { id: 'upper-limb', label: 'Upper Limb', sub: 'Shoulder · Elbow · Forearm · Wrist · Hand', icon: '💪', color: '#5A7A62', status: 'ready' },
  { id: 'lower-limb', label: 'Lower Limb', sub: 'Pelvis · Knee · Ankle · Foot', icon: '🦵', color: '#B8943F', status: 'ready' },
  { id: 'trunk-spine', label: 'Trunk & Spine', sub: 'Vertebral column · Thorax', icon: '🧍', color: '#4A6FA5', status: 'ready' },
  { id: 'head-neck', label: 'Head & Neck', sub: 'Skull · Cervical spine · Face', icon: '🧠', color: '#9B59B6', status: 'ready' },
];

// ─── VIDEOS ──────────────────────────────────────────────
// Reference videos per region. youtubeId is the 11-char video ID
// (parsed from youtu.be/<id> links). Each entry renders as a card with an
// in-app player button and an "Open on YouTube" button.
const ANATOMY_VIDEOS = {
  'upper-limb': [
    { id:'ul-1', title:'Upper Limb Anatomy Overview', youtubeId:'crC-0WAWrdc' },
  ],
  'lower-limb': [
    { id:'ll-1', title:'Lower Limb Anatomy Overview', youtubeId:'o8-jI-TX0nI' },
  ],
  'trunk-spine': [
    { id:'ts-1', title:'Spine Anatomy Overview', youtubeId:'N28uEWxhH8I' },
    { id:'ts-2', title:'Core / Trunk Anatomy Overview', youtubeId:'9gB9PEHP-Ok' },
  ],
  'head-neck': [
    { id:'hn-1', title:'Muscles of the Head & Neck', youtubeId:'F_O0Rj3IWn8' },
    { id:'hn-2', title:'Bones of the Skull', youtubeId:'34jeggKoNiM' },
  ],
};

// ─── BONES ───────────────────────────────────────────────
const ANATOMY_BONES = {
  'upper-limb': [
    { id:'clavicle', name:'Clavicle', group:'Shoulder Girdle',
      summary:'The collarbone — an S-shaped strut that braces the shoulder out from the sternum.',
      details:'Runs horizontally between the sternum (medial end) and the acromion of the scapula (lateral end). It is one of the most commonly fractured bones (often from a fall onto an outstretched hand or a direct blow to the shoulder), and it is also the first long bone in the body to begin ossifying in the embryo.',
      landmarks:['Sternal (medial) end', 'Acromial (lateral) end', 'Conoid tubercle'] },
    { id:'scapula', name:'Scapula', group:'Shoulder Girdle',
      summary:'The flat, triangular "shoulder blade" that floats over the ribcage, anchored only by muscle.',
      details:'Provides the socket (glenoid fossa) for the humeral head and a broad surface for many shoulder muscles to attach. Its mobility on the rib cage (scapulothoracic motion) is essential for full overhead reach — this is the basis of "scapulohumeral rhythm", where for roughly every 3° of arm elevation about 2° comes from the shoulder joint and 1° from scapular rotation.',
      landmarks:['Glenoid fossa', 'Acromion process', 'Coracoid process', 'Spine of scapula', 'Superior/inferior angle'] },
    { id:'humerus', name:'Humerus', group:'Arm',
      summary:'The single long bone of the upper arm, from shoulder to elbow.',
      details:'Its rounded head sits in the glenoid fossa to form the very mobile (but less stable) glenohumeral joint. Distally it flares into two condyles (capitulum and trochlea) that articulate with the radius and ulna at the elbow. The radial (spiral) groove on its posterior shaft carries the radial nerve — a fracture here is a classic cause of wrist drop.',
      landmarks:['Head', 'Greater & lesser tubercle', 'Deltoid tuberosity', 'Medial/lateral epicondyle', 'Capitulum', 'Trochlea'] },
    { id:'radius', name:'Radius', group:'Forearm',
      summary:'The lateral (thumb-side) forearm bone — it rotates around the ulna to turn the palm up or down.',
      details:'Small proximally (radial head), wide distally, opposite of the ulna. Its rotation at the proximal and distal radioulnar joints produces pronation and supination. A fall onto an outstretched hand classically fractures the distal radius (a "Colles\' fracture").',
      landmarks:['Radial head', 'Radial tuberosity', 'Styloid process'] },
    { id:'ulna', name:'Ulna', group:'Forearm',
      summary:'The medial (pinky-side) forearm bone — large proximally, forms the main elbow hinge.',
      details:'Its olecranon and trochlear notch wrap around the humeral trochlea, giving the elbow its stable hinge motion. It stays relatively fixed while the radius rotates around it.',
      landmarks:['Olecranon process', 'Trochlear notch', 'Coronoid process', 'Styloid process'] },
    { id:'carpals', name:'Carpal Bones (×8)', group:'Wrist',
      summary:'Two rows of four small bones that make up the wrist.',
      details:'Proximal row: Scaphoid, Lunate, Triquetrum, Pisiform. Distal row: Trapezium, Trapezoid, Capitate, Hamate. The scaphoid is the most frequently fractured carpal bone (classic "fall on outstretched hand" injury) and is prone to non-union/avascular necrosis because its blood supply enters distally and runs backward through the bone. A common memory aid for the 8 carpals (proximal → distal, lateral → medial) is "Some Lovers Try Positions That They Can\'t Handle".',
      landmarks:['Scaphoid', 'Lunate', 'Triquetrum', 'Pisiform', 'Trapezium', 'Trapezoid', 'Capitate', 'Hamate'] },
    { id:'metacarpals', name:'Metacarpals (×5)', group:'Hand',
      summary:'The five bones forming the palm, one per finger/thumb ray.',
      details:'Numbered 1 (thumb) to 5 (little finger). Their heads form the knuckles (MCP joints).',
      landmarks:['Base', 'Shaft', 'Head'] },
    { id:'phalanges', name:'Phalanges', group:'Hand',
      summary:'The finger and thumb bones — 14 in total per hand.',
      details:'The thumb has 2 (proximal, distal); each finger has 3 (proximal, middle, distal).',
      landmarks:['Proximal phalanx', 'Middle phalanx', 'Distal phalanx'] },
  ],
  'lower-limb': [
    { id:'hip-bone', name:'Os Coxae (Hip Bone)', group:'Pelvis',
      summary:'The large fused bone forming each side of the pelvis — three bones become one in adulthood.',
      details:'Formed by fusion of the Ilium (upper wing), Ischium (lower, weight-bearing in sitting), and Pubis (anterior, meets its pair at the pubic symphysis). Together the two hip bones plus the sacrum form the pelvic ring.',
      landmarks:['Iliac crest', 'ASIS / PSIS', 'Ischial tuberosity', 'Ischial spine', 'Pubic tubercle', 'Acetabulum'] },
    { id:'sacrum', name:'Sacrum', group:'Pelvis',
      summary:'A triangular bone made of 5 fused vertebrae, wedged between the two hip bones.',
      details:'Transmits body weight from the spine down into the pelvis via the sacroiliac joints, and forms the posterior wall of the pelvic ring.',
      landmarks:['Sacral ala', 'Sacral promontory', 'Auricular surface'] },
    { id:'femur', name:'Femur', group:'Thigh',
      summary:'The longest, strongest bone in the body — from hip to knee.',
      details:'Its head sits in the acetabulum to form the hip joint; the neck between head and shaft is a common fracture site in osteoporotic falls ("broken hip"). The greater and lesser trochanters are major muscle-attachment landmarks.',
      landmarks:['Head', 'Neck', 'Greater trochanter', 'Lesser trochanter', 'Linea aspera', 'Medial/lateral condyle', 'Medial/lateral epicondyle'] },
    { id:'patella', name:'Patella', group:'Knee',
      summary:'The kneecap — the largest sesamoid bone in the body, embedded in the quadriceps tendon.',
      details:'Increases the mechanical advantage (leverage) of the quadriceps by holding its tendon away from the knee\'s center of rotation.',
      landmarks:['Apex', 'Base', 'Articular (posterior) surface'] },
    { id:'tibia', name:'Tibia', group:'Leg',
      summary:'The shin bone — the main weight-bearing bone of the lower leg.',
      details:'Its proximal condyles articulate with the femur to form the knee; distally, the medial malleolus forms the inner ankle bump.',
      landmarks:['Medial/lateral condyle', 'Tibial tuberosity', 'Medial malleolus'] },
    { id:'fibula', name:'Fibula', group:'Leg',
      summary:'The thin, non-weight-bearing bone on the outside of the lower leg.',
      details:'Mainly a site for muscle attachment and ankle stability; its distal end forms the lateral malleolus (outer ankle bump).',
      landmarks:['Head', 'Lateral malleolus'] },
    { id:'tarsals', name:'Tarsal Bones (×7)', group:'Foot',
      summary:'Seven bones making up the ankle/rearfoot — the foot\'s equivalent of the carpals.',
      details:'Talus (sits under the tibia — the only tarsal with no muscle attachments, moved entirely by the bones around it), Calcaneus (heel bone — largest tarsal, receives the Achilles tendon), Navicular, Cuboid, and three Cuneiforms (Medial, Intermediate, Lateral).',
      landmarks:['Talus', 'Calcaneus', 'Navicular', 'Cuboid', 'Medial/Intermediate/Lateral Cuneiform'] },
    { id:'metatarsals', name:'Metatarsals (×5)', group:'Foot',
      summary:'Five long bones forming the midfoot, one per toe ray.', details:'Numbered 1 (big toe) to 5 (little toe); their heads form the ball of the foot (MTP joints).',
      landmarks:['Base', 'Shaft', 'Head'] },
    { id:'foot-phalanges', name:'Phalanges (Toes)', group:'Foot',
      summary:'The toe bones — 14 per foot, mirroring the fingers.', details:'The big toe has 2 (proximal, distal); each other toe has 3.',
      landmarks:['Proximal phalanx', 'Middle phalanx', 'Distal phalanx'] },
  ],
  'trunk-spine': [
    { id:'cervical-vert', name:'Cervical Vertebrae (C1–C7)', group:'Vertebral Column',
      summary:'The 7 neck vertebrae — the smallest and most mobile of the spine.',
      details:'C1 (the Atlas) has no vertebral body and simply cradles the skull, nodding "yes" at the atlanto-occipital joint. C2 (the Axis) has a bony peg (the dens/odontoid process) that C1 pivots around, producing the "no" head-shake rotation.',
      landmarks:['Atlas (C1)', 'Axis (C2) — dens/odontoid process', 'Transverse foramen (carries the vertebral artery)', 'Bifid spinous process (C2–C6)'] },
    { id:'thoracic-vert', name:'Thoracic Vertebrae (T1–T12)', group:'Vertebral Column',
      summary:'The 12 mid-back vertebrae, each one paired with a rib.',
      details:'Have costal facets for rib articulation and long, downward-sloping spinous processes; the least mobile spinal region, partly because the rib cage limits motion.',
      landmarks:['Costal facets (for rib heads)', 'Long spinous process'] },
    { id:'lumbar-vert', name:'Lumbar Vertebrae (L1–L5)', group:'Vertebral Column',
      summary:'The 5 low-back vertebrae — the largest, built to bear the most load.',
      details:'Thick vertebral bodies and stubby spinous processes; this region allows generous flexion/extension but limited rotation.',
      landmarks:['Large vertebral body', 'Mammillary process'] },
    { id:'sacrum-coccyx', name:'Sacrum & Coccyx', group:'Vertebral Column',
      summary:'The sacrum (5 fused vertebrae) and coccyx (3–5 fused vertebrae) form the base of the spine.',
      details:'The sacrum links the spine to the pelvis via the sacroiliac joints; the coccyx ("tailbone") is a small vestigial attachment point for pelvic floor muscles.' },
    { id:'ribs', name:'Ribs (12 pairs)', group:'Thorax',
      summary:'Curved bones forming the rib cage, protecting the heart and lungs.',
      details:'Ribs 1–7 are "true ribs" (attach directly to the sternum via costal cartilage); 8–10 are "false ribs" (attach indirectly, to the cartilage above); 11–12 are "floating ribs" (no anterior attachment at all).',
      landmarks:['Head', 'Neck', 'Tubercle', 'Costal cartilage'] },
    { id:'sternum', name:'Sternum', group:'Thorax',
      summary:'The flat breastbone at the front of the rib cage.',
      details:'Made of the Manubrium (upper), Body, and Xiphoid process (lower tip) — the manubriosternal joint between the first two ("sternal angle") is a useful landmark for locating the 2nd rib.',
      landmarks:['Manubrium', 'Body', 'Xiphoid process'] },
  ],
  'head-neck': [
    { id:'frontal', name:'Frontal Bone', group:'Cranium', summary:'Forms the forehead and roof of the eye sockets.' },
    { id:'parietal', name:'Parietal Bones (×2)', group:'Cranium', summary:'Form most of the roof and sides of the skull, meeting at the sagittal suture.' },
    { id:'temporal', name:'Temporal Bones (×2)', group:'Cranium',
      summary:'House the ear structures and form part of the TMJ.',
      details:'Contains the mandibular fossa (socket for the jaw joint) and the mastoid process (a muscle-attachment landmark you can feel behind the ear).',
      landmarks:['Mastoid process', 'Mandibular fossa', 'Styloid process'] },
    { id:'occipital', name:'Occipital Bone', group:'Cranium',
      summary:'Forms the back and base of the skull.',
      details:'Contains the foramen magnum, where the spinal cord passes through, and the occipital condyles that articulate with C1 (the atlas).',
      landmarks:['Foramen magnum', 'Occipital condyles'] },
    { id:'sphenoid', name:'Sphenoid Bone', group:'Cranium', summary:'A butterfly-shaped bone at the base of the skull that articulates with nearly every other cranial bone.' },
    { id:'mandible', name:'Mandible', group:'Face',
      summary:'The lower jaw — the only mobile bone of the skull.',
      details:'Articulates with the temporal bone at the TMJ; its condyle, ramus, and angle are key palpation landmarks for jaw assessment.',
      landmarks:['Condyle', 'Ramus', 'Angle', 'Body'] },
    { id:'maxilla', name:'Maxilla (×2)', group:'Face', summary:'Forms the upper jaw and much of the hard palate and eye-socket floor.' },
    { id:'hyoid', name:'Hyoid Bone', group:'Neck',
      summary:'A small U-shaped bone in the neck that articulates with no other bone.',
      details:'Suspended by muscles and ligaments only; anchors tongue and swallowing (suprahyoid/infrahyoid) muscles.' },
    { id:'atlas-axis', name:'Atlas (C1) & Axis (C2)', group:'Craniocervical Junction',
      summary:'The two highly specialized top cervical vertebrae that carry and rotate the skull.',
      details:'The Atlas has no body and cradles the occipital condyles (nodding "yes"); the Axis has the dens, a peg the Atlas pivots around (shaking "no").',
      landmarks:['Dens (odontoid process)', 'Anterior/posterior arch of C1'] },
  ]
};

// ─── JOINTS ──────────────────────────────────────────────
const ANATOMY_JOINTS = {
  'upper-limb': [
    { id:'sternoclavicular', name:'Sternoclavicular (SC) Joint', type:'Saddle',
      summary:'The only bony connection between the arm and the axial skeleton.',
      extra:'Despite carrying the entire load of the upper limb through it, this small joint is stabilized mainly by strong ligaments (costoclavicular, interclavicular) rather than bone shape.' },
    { id:'acromioclavicular', name:'Acromioclavicular (AC) Joint', type:'Plane/gliding',
      summary:'Where the clavicle meets the acromion; a common site of "separated shoulder" injuries from a fall onto the shoulder tip.',
      extra:'AC separations are graded I–VI based on how many of the AC and coracoclavicular ligaments are torn.' },
    { id:'glenohumeral', name:'Glenohumeral (GH) Joint', type:'Ball and socket',
      summary:'The main shoulder joint — the most mobile joint in the body, which is exactly why it is also the least stable and most frequently dislocated.',
      extra:'The glenoid fossa is shallow and only covers about a third of the humeral head — often compared to "a golf ball sitting on a tee". Stability relies heavily on the rotator cuff and the labrum (a fibrocartilage rim).' },
    { id:'elbow-complex', name:'Elbow Joint Complex', type:'Hinge (humeroulnar) + pivot (humeroradial)',
      summary:'Functions as a hinge for flexion/extension while the radial head also rotates for pronation/supination.',
      extra:'All three elbow articulations (humeroulnar, humeroradial, proximal radioulnar) share one joint capsule.' },
    { id:'radioulnar', name:'Radioulnar Joints (proximal + distal)', type:'Pivot',
      summary:'Working together, these two joints let the radius rotate around the ulna to pronate/supinate the forearm.',
      extra:'The interosseous membrane connecting the radius and ulna also helps transmit force from the hand up to the elbow.' },
    { id:'wrist', name:'Wrist (Radiocarpal) Joint', type:'Condyloid',
      summary:'Between the distal radius and the proximal carpal row; allows flexion, extension, radial/ulnar deviation.' },
    { id:'hand-joints', name:'Hand Joints (CMC, MCP, IP)', type:'Saddle / condyloid / hinge',
      summary:'CMC joints (base of fingers) mostly glide; MCP knuckles allow flexion + some ab/adduction; IP joints are pure hinges.',
      extra:'The thumb\'s CMC joint is the exception — its true saddle shape gives it the extra freedom needed for opposition.' },
  ],
  'lower-limb': [
    { id:'sacroiliac', name:'Sacroiliac (SI) Joint', type:'Synovial (anterior) + fibrous/ligamentous (posterior)',
      summary:'Where the sacrum meets each hip bone; transfers load between the spine and lower limbs.',
      extra:'Very little motion normally occurs here — its main job is load transfer and shock absorption, not mobility.' },
    { id:'hip', name:'Hip Joint', type:'Ball and socket',
      summary:'Where the femoral head meets the deep, cup-shaped acetabulum.',
      extra:'Unlike the shoulder, the hip\'s socket is deep and reinforced by a strong capsule and ligaments — trading some mobility for much greater inherent stability.' },
    { id:'knee', name:'Knee Joint (Tibiofemoral + Patellofemoral)', type:'Modified hinge',
      summary:'The body\'s largest joint — mainly flexion/extension, with a small amount of rotation available only when the knee is flexed.',
      extra:'Two C-shaped menisci (medial & lateral) deepen the shallow tibial plateau and help distribute load and absorb shock.' },
    { id:'prox-tib-fib', name:'Proximal Tibiofibular Joint', type:'Plane/gliding',
      summary:'Small joint between the fibular head and the lateral tibial condyle.' },
    { id:'dist-tib-fib', name:'Distal Tibiofibular Joint', type:'Fibrous (syndesmosis)',
      summary:'Holds the tibia and fibula together just above the ankle, forming the "mortise" the talus sits in.',
      extra:'A "high ankle sprain" is an injury to this joint\'s ligaments rather than the more common lateral ankle ligaments.' },
    { id:'talocrural', name:'Ankle (Talocrural) Joint', type:'Hinge',
      summary:'Between the tibia/fibula "mortise" and the talus — allows dorsiflexion and plantarflexion.' },
    { id:'subtalar', name:'Subtalar Joint', type:'Plane/gliding',
      summary:'Between the talus and calcaneus; produces inversion and eversion of the foot.' },
    { id:'foot-joints', name:'Foot Joints (Midtarsal, Tarsometatarsal, MTP, IP)', type:'Mixed (gliding, hinge)',
      summary:'The midtarsal (Chopart\'s) joint and tarsometatarsal (Lisfranc) joint let the midfoot twist slightly for shock absorption; MTP and IP joints move the toes.' },
  ],
  'trunk-spine': [
    { id:'facet-joints', name:'Facet (Zygapophyseal) Joints', type:'Plane/gliding',
      summary:'Paired joints on the back of each vertebra that guide and limit spinal motion.',
      extra:'Their orientation changes by region — roughly vertical in the cervical spine (favoring rotation), close to the frontal plane in the thoracic spine (limiting flexion/extension), and near-sagittal in the lumbar spine (favoring flexion/extension, limiting rotation).' },
    { id:'iv-disc', name:'Intervertebral Discs', type:'Fibrocartilaginous (symphysis)',
      summary:'Shock-absorbing cushions between vertebral bodies, made of a tough outer ring (annulus fibrosus) around a gel-like center (nucleus pulposus).',
      extra:'A "slipped disc" (herniation) happens when the nucleus pushes through a tear in the annulus, often compressing a nearby nerve root.' },
    { id:'costovertebral', name:'Costovertebral & Costotransverse Joints', type:'Plane/gliding',
      summary:'Where each rib head and tubercle meet the vertebrae — allow the small gliding motion needed for breathing.' },
    { id:'sternocostal', name:'Sternocostal Joints', type:'Mixed (cartilaginous 1st rib; synovial ribs 2–7)',
      summary:'Where the true ribs\' costal cartilages attach to the sternum.' },
  ],
  'head-neck': [
    { id:'atlanto-occipital', name:'Atlanto-Occipital (AO) Joint', type:'Condyloid',
      summary:'Between the skull\'s occipital condyles and the atlas (C1) — produces the head-nodding "yes" motion.' },
    { id:'atlantoaxial', name:'Atlantoaxial (AA) Joint', type:'Pivot',
      summary:'Between the atlas (C1) and the dens of the axis (C2) — produces roughly half of all cervical rotation, the head-shaking "no" motion.' },
    { id:'tmj', name:'Temporomandibular Joint (TMJ)', type:'Hinge + gliding (compound synovial)',
      summary:'Between the mandibular condyle and the temporal bone — combines a hinge (opening/closing) with forward gliding, using an articular disc to smooth the two motions.',
      extra:'One of the only joints in the body used constantly for chewing, speaking, and swallowing — and the two sides must always move together.' },
    { id:'cervical-facets', name:'Cervical Facet Joints (C3–C7)', type:'Plane/gliding',
      summary:'Oriented close to 45° in the cervical spine, allowing generous combined flexion, extension, and rotation compared to the rest of the spine.' },
  ],
};

// ─── MUSCLES (grouped) ───────────────────────────────────
const ANATOMY_MUSCLE_GROUPS = {
  'upper-limb': [
    { group: 'Superficial Shoulder Movers', muscles: [
      { id:'deltoid', name:'Deltoid', origin:'Lateral 1/3 of clavicle, acromion, spine of scapula', insertion:'Deltoid tuberosity of humerus',
        action:'Anterior fibers flex/internally rotate; middle fibers abduct; posterior fibers extend/externally rotate the shoulder.',
        nerve:'Axillary nerve (C5–C6)',
        note:'The main prime mover for shoulder abduction after the first ~15° (which supraspinatus initiates).' },
      { id:'pec-major', name:'Pectoralis Major', origin:'Clavicle, sternum, upper costal cartilages', insertion:'Lateral lip of bicipital groove (humerus)',
        action:'Flexes, adducts, and internally rotates the shoulder.',
        nerve:'Medial & lateral pectoral nerves (C5–T1)',
        note:'Big, powerful "pushing" muscle — think push-ups and bench press.' },
      { id:'lat-dorsi', name:'Latissimus Dorsi', origin:'Lower thoracic/lumbar spine, iliac crest, lower ribs', insertion:'Floor of bicipital groove (humerus)',
        action:'Extends, adducts, and internally rotates the shoulder.',
        nerve:'Thoracodorsal nerve (C6–C8)',
        note:'The "climbing" muscle — pulling the body up toward a fixed arm (pull-ups).' },
      { id:'trapezius', name:'Trapezius', origin:'Occiput, spinous processes C7–T12', insertion:'Clavicle, acromion, spine of scapula',
        action:'Upper fibers elevate; middle fibers retract; lower fibers depress the scapula — together they upwardly rotate it for overhead reach.',
        nerve:'Accessory nerve (Cranial Nerve XI), with sensory/proprioceptive fibers from C3–C4',
        note:'Often overworked/tight in people who sit at a desk all day.' },
      { id:'teres-major', name:'Teres Major', origin:'Inferior angle of scapula', insertion:'Medial lip of bicipital groove (humerus)',
        action:'Extends, adducts, internally rotates the shoulder.',
        nerve:'Lower subscapular nerve (C5–C7)',
        note:"Nicknamed \"lat's little helper\" for sharing latissimus dorsi's action." },
    ]},
    { group: 'Rotator Cuff (Deep Stabilizers)', muscles: [
      { id:'supraspinatus', name:'Supraspinatus', origin:'Supraspinous fossa of scapula', insertion:'Greater tubercle of humerus',
        action:'Initiates the first ~15° of shoulder abduction and stabilizes the humeral head in the glenoid.',
        nerve:'Suprascapular nerve (C5–C6)',
        note:'The most commonly injured rotator-cuff muscle/tendon.' },
      { id:'infraspinatus', name:'Infraspinatus', origin:'Infraspinous fossa of scapula', insertion:'Greater tubercle of humerus',
        action:'Externally rotates the shoulder; stabilizes the humeral head.',
        nerve:'Suprascapular nerve (C5–C6)' },
      { id:'teres-minor', name:'Teres Minor', origin:'Lateral border of scapula', insertion:'Greater tubercle of humerus',
        action:'Externally rotates the shoulder; stabilizes the humeral head.',
        nerve:'Axillary nerve (C5–C6)' },
      { id:'subscapularis', name:'Subscapularis', origin:'Subscapular fossa (anterior scapula)', insertion:'Lesser tubercle of humerus',
        action:'Internally rotates the shoulder; stabilizes the humeral head (the only rotator-cuff muscle on the front of the scapula).',
        nerve:'Upper & lower subscapular nerves (C5–C7)',
        note:'Easy memory aid for the 4 rotator cuff muscles: "SItS" — Supraspinatus, Infraspinatus, teres minor, Subscapularis.' },
    ]},
    { group: 'Scapular Stabilizers', muscles: [
      { id:'rhomboids', name:'Rhomboids (Major & Minor)', origin:'Spinous processes C7–T5', insertion:'Medial border of scapula',
        action:'Retract and downwardly rotate the scapula; hold the scapula against the rib cage.',
        nerve:'Dorsal scapular nerve (C4–C5)' },
      { id:'levator-scap', name:'Levator Scapulae', origin:'Transverse processes C1–C4', insertion:'Superior angle of scapula',
        action:'Elevates the scapula; helps rotate the neck.',
        nerve:'Dorsal scapular nerve and direct branches of C3–C4',
        note:'Common source of "stiff neck" tightness.' },
      { id:'serratus-ant', name:'Serratus Anterior', origin:'Ribs 1–8/9 (lateral surface)', insertion:'Medial border of scapula (anterior surface)',
        action:'Protracts the scapula and rotates it upward — essential for full overhead pushing/punching motions.',
        nerve:'Long thoracic nerve (C5–C7)',
        note:'Weakness (e.g. from long thoracic nerve injury) causes a "winged scapula".' },
    ]},
    { group: 'Elbow & Forearm Movers', muscles: [
      { id:'biceps-brachii', name:'Biceps Brachii', origin:'Long head: supraglenoid tubercle; Short head: coracoid process', insertion:'Radial tuberosity',
        action:'Flexes the elbow and supinates the forearm; assists shoulder flexion.',
        nerve:'Musculocutaneous nerve (C5–C6)' },
      { id:'triceps-brachii', name:'Triceps Brachii', origin:'Long head: infraglenoid tubercle; Lateral & medial heads: posterior humerus', insertion:'Olecranon process of ulna',
        action:'Extends the elbow; the long head also assists shoulder extension.',
        nerve:'Radial nerve (C6–C8)' },
      { id:'brachialis', name:'Brachialis', origin:'Distal anterior humerus', insertion:'Coronoid process of ulna',
        action:'Pure elbow flexor — works regardless of forearm position (unlike biceps).',
        nerve:'Musculocutaneous nerve, with a small contribution from the radial nerve (C5–C6)' },
      { id:'brachioradialis', name:'Brachioradialis', origin:'Lateral supracondylar ridge of humerus', insertion:'Styloid process of radius',
        action:'Flexes the elbow; strongest when the forearm is in mid-pronation ("hammer curl" muscle).',
        nerve:'Radial nerve (C5–C6)',
        note:'Unusual for being a forearm muscle innervated by the radial nerve yet acting purely as a flexor.' },
      { id:'pronator-teres', name:'Pronator Teres', origin:'Medial epicondyle of humerus, coronoid process of ulna', insertion:'Lateral surface of radius',
        action:'Pronates the forearm (turns palm down); assists elbow flexion.',
        nerve:'Median nerve (C6–C7)' },
      { id:'supinator', name:'Supinator', origin:'Lateral epicondyle of humerus, proximal ulna', insertion:'Proximal lateral radius',
        action:'Supinates the forearm (turns palm up).',
        nerve:'Deep branch of the radial nerve / posterior interosseous nerve (C5–C6)' },
    ]},
    { group: 'Wrist & Finger Movers (Extrinsic)', muscles: [
      { id:'fcr', name:'Flexor Carpi Radialis', origin:'Medial epicondyle of humerus', insertion:'Base of 2nd/3rd metacarpal',
        action:'Flexes and radially deviates the wrist.',
        nerve:'Median nerve (C6–C7)' },
      { id:'fcu', name:'Flexor Carpi Ulnaris', origin:'Medial epicondyle, olecranon', insertion:'Pisiform, hamate, 5th metacarpal',
        action:'Flexes and ulnarly deviates the wrist.',
        nerve:'Ulnar nerve (C7–T1)' },
      { id:'fds', name:'Flexor Digitorum Superficialis', origin:'Medial epicondyle, radius', insertion:'Middle phalanges of fingers 2–5',
        action:'Flexes the PIP joints (and assists MCP/wrist flexion).',
        nerve:'Median nerve (C7–T1)' },
      { id:'ecrl-b', name:'Extensor Carpi Radialis Longus & Brevis', origin:'Lateral supracondylar ridge / lateral epicondyle', insertion:'Base of 2nd/3rd metacarpal',
        action:'Extend and radially deviate the wrist.',
        nerve:'Radialis longus: radial nerve; Radialis brevis: posterior interosseous nerve (C5–C7)' },
      { id:'ecu', name:'Extensor Carpi Ulnaris', origin:'Lateral epicondyle, ulna', insertion:'Base of 5th metacarpal',
        action:'Extends and ulnarly deviates the wrist.',
        nerve:'Posterior interosseous nerve, a branch of the radial nerve (C7–C8)' },
      { id:'ed', name:'Extensor Digitorum', origin:'Lateral epicondyle of humerus', insertion:'Extensor expansions of fingers 2–5',
        action:'Extends the fingers and assists wrist extension.',
        nerve:'Posterior interosseous nerve, a branch of the radial nerve (C7–C8)' },
    ]},
    { group: 'Intrinsic Hand Muscles', muscles: [
      { id:'thenar', name:'Thenar Group (Abd./Flex./Opponens Pollicis Brevis)', origin:'Flexor retinaculum, carpal bones', insertion:'Base of thumb (1st metacarpal/proximal phalanx)',
        action:'Abduct, flex, and oppose the thumb — the base of the thumb pad.',
        nerve:'Recurrent (motor) branch of the median nerve',
        note:'This nerve branch runs very superficially, which is why the thenar eminence is the classic muscle group tested for carpal tunnel syndrome.' },
      { id:'hypothenar', name:'Hypothenar Group (Abd./Flex./Opponens Digiti Minimi)', origin:'Flexor retinaculum, hamate', insertion:'Base of little finger (5th metacarpal/proximal phalanx)',
        action:'Abduct, flex, and oppose the little finger — the base of the pinky pad.',
        nerve:'Deep branch of the ulnar nerve' },
      { id:'lumbricals', name:'Lumbricals', origin:'Tendons of flexor digitorum profundus', insertion:'Extensor expansions of fingers',
        action:'Flex the MCP joints while extending the IP joints — the classic "pen-holding" position.',
        nerve:'Lumbricals 1–2 (index/middle): median nerve; Lumbricals 3–4 (ring/little): deep branch of ulnar nerve' },
      { id:'interossei', name:'Interossei (Palmar & Dorsal)', origin:'Shafts of metacarpals', insertion:'Base of proximal phalanges / extensor expansions',
        action:'Palmar interossei ADduct the fingers; dorsal interossei ABduct the fingers ("PAD/DAB" rule). Both assist lumbricals at the MCP/IP joints.',
        nerve:'Deep branch of the ulnar nerve' },
    ]},
  ],
  'lower-limb': [
    { group: 'Hip Flexors', muscles: [
      { id:'iliopsoas', name:'Iliopsoas (Iliacus + Psoas Major)', origin:'Iliacus: iliac fossa; Psoas major: transverse processes/bodies of T12–L5', insertion:'Lesser trochanter of femur',
        action:'The strongest hip flexor; psoas major also assists trunk flexion/lateral flexion of the lumbar spine.',
        nerve:'Iliacus: femoral nerve; Psoas major: direct branches of the lumbar plexus (L1–L4)' },
      { id:'sartorius', name:'Sartorius', origin:'ASIS', insertion:'Proximal medial tibia (pes anserinus)',
        action:'Flexes, abducts, and externally rotates the hip; also flexes the knee — the classic "cross-legged sitting" muscle and the longest muscle in the body.',
        nerve:'Femoral nerve (L2–L3)' },
      { id:'tfl', name:'Tensor Fasciae Latae (TFL)', origin:'ASIS', insertion:'Iliotibial (IT) band',
        action:'Flexes, abducts, and internally rotates the hip; tensions the IT band to help stabilize the knee in stance.',
        nerve:'Superior gluteal nerve (L4–S1)' },
    ]},
    { group: 'Hip Extensors & Gluteals', muscles: [
      { id:'glut-max', name:'Gluteus Maximus', origin:'Posterior ilium, sacrum, coccyx', insertion:'Gluteal tuberosity of femur & IT band',
        action:'The primary hip extensor, especially strong from a flexed position (e.g. rising from sitting, climbing stairs); also externally rotates the hip.',
        nerve:'Inferior gluteal nerve (L5–S2)' },
      { id:'glut-med', name:'Gluteus Medius', origin:'Lateral ilium', insertion:'Greater trochanter of femur',
        action:'Abducts the hip; critically, it stabilizes the pelvis in single-leg stance (weakness causes a Trendelenburg gait/pelvic drop).',
        nerve:'Superior gluteal nerve (L4–S1)' },
      { id:'glut-min', name:'Gluteus Minimus', origin:'Lateral ilium (deep to gluteus medius)', insertion:'Greater trochanter of femur',
        action:'Abducts and internally rotates the hip; assists gluteus medius in pelvic stabilization.',
        nerve:'Superior gluteal nerve (L4–S1)' },
      { id:'piriformis', name:'Piriformis', origin:'Anterior sacrum', insertion:'Greater trochanter of femur',
        action:'Externally rotates the hip when it is extended; represents the "deep lateral rotator" group.',
        nerve:'Nerve to piriformis (S1–S2)',
        note:'The sciatic nerve usually runs just beneath (sometimes through) this muscle — spasm here can mimic sciatica ("piriformis syndrome").' },
    ]},
    { group: 'Hip Adductors', muscles: [
      { id:'add-longus', name:'Adductor Longus', origin:'Pubis', insertion:'Middle third of linea aspera (femur)',
        action:'Adducts and assists flexion of the hip.', nerve:'Obturator nerve (L2–L4)' },
      { id:'add-brevis', name:'Adductor Brevis', origin:'Pubis', insertion:'Proximal linea aspera (femur)',
        action:'Adducts the hip.', nerve:'Obturator nerve (L2–L4)' },
      { id:'add-magnus', name:'Adductor Magnus', origin:'Pubis and ischial tuberosity', insertion:'Linea aspera and adductor tubercle (femur)',
        action:'Its adductor part adducts the hip; its posterior ("hamstring") part assists hip extension.',
        nerve:'Adductor part: obturator nerve; Hamstring part: tibial division of the sciatic nerve (L2–S1)' },
      { id:'gracilis', name:'Gracilis', origin:'Pubis', insertion:'Proximal medial tibia (pes anserinus)',
        action:'Adducts the hip and flexes the knee — a thin, strap-like muscle running the full length of the inner thigh.',
        nerve:'Obturator nerve (L2–L4)' },
      { id:'pectineus', name:'Pectineus', origin:'Pubis (pectineal line)', insertion:'Pectineal line of femur (below lesser trochanter)',
        action:'Adducts and flexes the hip.', nerve:'Femoral nerve, with a variable contribution from the obturator nerve (L2–L4)' },
    ]},
    { group: 'Knee Extensors — Quadriceps', muscles: [
      { id:'rectus-femoris', name:'Rectus Femoris', origin:'AIIS (straight head) & superior acetabular rim (reflected head)', insertion:'Patella → tibial tuberosity (via patellar tendon)',
        action:'Extends the knee AND flexes the hip — the only quadriceps muscle that crosses both joints.',
        nerve:'Femoral nerve (L2–L4)' },
      { id:'vastus-lat', name:'Vastus Lateralis', origin:'Lateral femur', insertion:'Patella → tibial tuberosity',
        action:'Extends the knee; the largest of the four quadriceps heads.', nerve:'Femoral nerve (L2–L4)' },
      { id:'vastus-med', name:'Vastus Medialis', origin:'Medial femur', insertion:'Patella → tibial tuberosity',
        action:'Extends the knee; its lower fibers (VMO) help track the patella properly in its groove.', nerve:'Femoral nerve (L2–L4)' },
      { id:'vastus-int', name:'Vastus Intermedius', origin:'Anterior femoral shaft (deep to rectus femoris)', insertion:'Patella → tibial tuberosity',
        action:'Extends the knee.', nerve:'Femoral nerve (L2–L4)' },
    ]},
    { group: 'Knee Flexors — Hamstrings', muscles: [
      { id:'biceps-fem', name:'Biceps Femoris', origin:'Long head: ischial tuberosity; Short head: linea aspera (femur)', insertion:'Head of fibula',
        action:'Flexes the knee and externally rotates it when flexed; long head also extends the hip.',
        nerve:'Long head: tibial division of the sciatic nerve; Short head: common fibular (peroneal) division of the sciatic nerve (L5–S2)' },
      { id:'semitendinosus', name:'Semitendinosus', origin:'Ischial tuberosity', insertion:'Proximal medial tibia (pes anserinus)',
        action:'Flexes the knee and internally rotates it when flexed; assists hip extension.',
        nerve:'Tibial division of the sciatic nerve (L5–S2)' },
      { id:'semimembranosus', name:'Semimembranosus', origin:'Ischial tuberosity', insertion:'Posteromedial tibial condyle',
        action:'Flexes the knee and internally rotates it when flexed; assists hip extension.',
        nerve:'Tibial division of the sciatic nerve (L5–S2)' },
      { id:'popliteus', name:'Popliteus', origin:'Lateral femoral condyle', insertion:'Posterior proximal tibia',
        action:'"Unlocks" the fully extended knee by internally rotating the tibia (or externally rotating the femur) to allow flexion to begin.',
        nerve:'Tibial nerve (L4–S1)' },
    ]},
    { group: 'Ankle Dorsiflexors', muscles: [
      { id:'tib-ant', name:'Tibialis Anterior', origin:'Lateral tibia', insertion:'Medial cuneiform & 1st metatarsal',
        action:'Dorsiflexes and inverts the foot; controls the foot as it lowers after heel strike (eccentric control).',
        nerve:'Deep fibular (peroneal) nerve (L4–L5)' },
      { id:'edl', name:'Extensor Digitorum Longus', origin:'Lateral tibial condyle, fibula', insertion:'Extensor expansions of toes 2–5',
        action:'Extends toes 2–5 and assists dorsiflexion.', nerve:'Deep fibular nerve (L4–S1)' },
      { id:'ehl', name:'Extensor Hallucis Longus', origin:'Middle fibula', insertion:'Distal phalanx of the big toe',
        action:'Extends the big toe and assists dorsiflexion.', nerve:'Deep fibular nerve (L4–S1)' },
    ]},
    { group: 'Ankle Plantarflexors & Invertors', muscles: [
      { id:'gastrocnemius', name:'Gastrocnemius', origin:'Medial & lateral femoral condyles', insertion:'Calcaneus (via Achilles tendon)',
        action:'Plantarflexes the ankle and assists knee flexion — the only calf muscle that crosses both joints.',
        nerve:'Tibial nerve (S1–S2)' },
      { id:'soleus', name:'Soleus', origin:'Posterior tibia & fibula', insertion:'Calcaneus (via Achilles tendon)',
        action:'Plantarflexes the ankle; unlike gastrocnemius, stays effective with the knee bent — key for standing posture endurance.',
        nerve:'Tibial nerve (S1–S2)' },
      { id:'tib-post', name:'Tibialis Posterior', origin:'Posterior tibia & fibula (interosseous membrane)', insertion:'Navicular and surrounding tarsals',
        action:'Plantarflexes and inverts the foot; the primary dynamic support for the medial longitudinal arch.',
        nerve:'Tibial nerve (L4–L5)' },
      { id:'fibularis', name:'Fibularis (Peroneus) Longus & Brevis', origin:'Lateral fibula', insertion:'Longus: 1st metatarsal/medial cuneiform; Brevis: base of 5th metatarsal',
        action:'Evert the foot and assist plantarflexion — key dynamic stabilizers against ankle-sprain (inversion) injuries.',
        nerve:'Superficial fibular (peroneal) nerve (L5–S1)' },
    ]},
    { group: 'Intrinsic Foot Muscles', muscles: [
      { id:'foot-intrinsics', name:'Foot Intrinsics (Abductor Hallucis, Flexor Digitorum Brevis, Lumbricals, Interossei, etc.)', origin:'Calcaneus and adjacent tarsals/plantar fascia', insertion:'Toe phalanges',
        action:'Fine-tune toe flexion/extension/ab-adduction and help maintain the foot\'s arches during gait.',
        nerve:'Medial & lateral plantar nerves (branches of the tibial nerve); the extensor digitorum/hallucis brevis on the dorsum are supplied by the deep fibular nerve.' },
    ]},
  ],
  'trunk-spine': [
    { group: 'Posterior Spinal Muscles', muscles: [
      { id:'erector-spinae', name:'Erector Spinae (Iliocostalis, Longissimus, Spinalis)', origin:'Sacrum, iliac crest, spinous/transverse processes (varies by column)', insertion:'Ribs, transverse/spinous processes, skull (varies by column)',
        action:'The main extensors of the spine; bilateral contraction extends the trunk, unilateral contraction laterally flexes it.',
        nerve:'Dorsal rami of spinal nerves (segmental, throughout the spine)' },
      { id:'multifidus', name:'Multifidus (Transversospinalis Group)', origin:'Transverse processes', insertion:'Spinous process 2–4 levels above',
        action:'A key deep spinal stabilizer, providing segment-by-segment control during movement; often specifically targeted in low-back-pain rehab.',
        nerve:'Dorsal rami of spinal nerves (segmental)' },
      { id:'quad-lumborum', name:'Quadratus Lumborum', origin:'Iliac crest', insertion:'12th rib and transverse processes of L1–L4',
        action:'Laterally flexes the trunk (hikes the hip when the trunk is fixed) and assists forced exhalation by fixing the 12th rib.',
        nerve:'Subcostal nerve (T12) and branches of the lumbar plexus (L1–L4)' },
    ]},
    { group: 'Abdominal Wall', muscles: [
      { id:'rectus-abd', name:'Rectus Abdominis', origin:'Pubic crest', insertion:'Costal cartilages of ribs 5–7, xiphoid process',
        action:'Flexes the trunk (spine) and compresses the abdomen; its tendinous intersections create the "six-pack" look.',
        nerve:'Thoracoabdominal nerves (T7–T11) and subcostal nerve (T12)' },
      { id:'ext-oblique', name:'External Oblique', origin:'Ribs 5–12', insertion:'Iliac crest, linea alba',
        action:'Flexes and laterally flexes the trunk; rotates the trunk to the OPPOSITE side.',
        nerve:'Thoracoabdominal nerves (T7–T11), subcostal nerve (T12)' },
      { id:'int-oblique', name:'Internal Oblique', origin:'Iliac crest, inguinal ligament', insertion:'Ribs 10–12, linea alba',
        action:'Flexes and laterally flexes the trunk; rotates the trunk to the SAME side (opposite fiber direction from external oblique).',
        nerve:'Thoracoabdominal nerves (T7–T11), subcostal nerve (T12), iliohypogastric & ilioinguinal nerves (L1)' },
      { id:'trans-abd', name:'Transversus Abdominis', origin:'Iliac crest, inguinal ligament, costal cartilages 7–12', insertion:'Linea alba',
        action:'The deepest abdominal muscle — compresses the abdominal contents and provides core/spinal stability rather than producing spinal movement.',
        nerve:'Thoracoabdominal nerves (T7–T11), subcostal nerve (T12), iliohypogastric & ilioinguinal nerves (L1)' },
    ]},
    { group: 'Respiratory Muscles', muscles: [
      { id:'diaphragm', name:'Diaphragm', origin:'Xiphoid process, lower costal cartilages, lumbar vertebrae', insertion:'Central tendon',
        action:'The primary muscle of inspiration — contracting flattens its dome, expanding the thoracic cavity and drawing air in.',
        nerve:'Phrenic nerve (C3–C5)',
        note:'Classic mnemonic: "C3, 4, 5 keep the diaphragm alive" — a high cervical spinal cord injury above this level can be fatal without ventilator support.' },
      { id:'intercostals', name:'Intercostals (External & Internal)', origin:'Inferior border of the rib above', insertion:'Superior border of the rib below',
        action:'External intercostals elevate the ribs (assist inspiration); internal intercostals depress the ribs (assist forced expiration).',
        nerve:'Intercostal nerves — ventral rami of T1–T11' },
    ]},
  ],
  'head-neck': [
    { group: 'Neck Movers', muscles: [
      { id:'scm', name:'Sternocleidomastoid (SCM)', origin:'Sternum & clavicle', insertion:'Mastoid process (temporal bone)',
        action:'Bilaterally: flexes the neck; Unilaterally: laterally flexes to the same side and rotates the head to the OPPOSITE side.',
        nerve:'Accessory nerve (Cranial Nerve XI), with proprioceptive fibers from C2–C3' },
      { id:'scalenes', name:'Scalenes (Anterior, Middle, Posterior)', origin:'Transverse processes of cervical vertebrae', insertion:'1st & 2nd ribs',
        action:'Laterally flex and rotate the neck; also elevate the upper ribs to assist forced inspiration.',
        nerve:'Ventral rami of cervical spinal nerves (C3–C8)',
        note:'The brachial plexus and subclavian artery pass between the anterior and middle scalenes — tightness here can contribute to thoracic outlet syndrome.' },
      { id:'longus-colli-capitis', name:'Longus Colli & Longus Capitis', origin:'Cervical/upper thoracic vertebrae', insertion:'Atlas and other cervical vertebrae / occipital bone',
        action:'The deep neck flexors — key postural stabilizers of the cervical spine, often targeted in "deep neck flexor" rehab exercises.',
        nerve:'Ventral rami of C1–C6' },
      { id:'splenius', name:'Splenius Capitis & Cervicis', origin:'Lower cervical/upper thoracic spinous processes', insertion:'Mastoid process / upper cervical transverse processes',
        action:'Bilaterally: extend the neck; Unilaterally: laterally flex and rotate the head to the SAME side.',
        nerve:'Dorsal rami of middle cervical spinal nerves' },
      { id:'suboccipitals', name:'Suboccipitals (Rectus Capitis Post. Major/Minor, Obliquus Capitis Sup./Inf.)', origin:'Atlas, axis, occipital bone (small group at the very top of the neck)', insertion:'Occipital bone / atlas',
        action:'Fine-tune small, precise movements of the head on the atlas — important for balance and visual fixation.',
        nerve:'Suboccipital nerve (dorsal ramus of C1)' },
    ]},
    { group: 'Muscles of Mastication', muscles: [
      { id:'masseter', name:'Masseter', origin:'Zygomatic arch', insertion:'Angle & ramus of mandible',
        action:'A powerful jaw elevator (closes the mouth/bites down).', nerve:'Mandibular division of the trigeminal nerve (CN V3)' },
      { id:'temporalis', name:'Temporalis', origin:'Temporal fossa', insertion:'Coronoid process of mandible',
        action:'Elevates the jaw; its posterior fibers also retract the mandible.', nerve:'CN V3' },
      { id:'pterygoids', name:'Medial & Lateral Pterygoid', origin:'Sphenoid bone', insertion:'Medial: angle of mandible; Lateral: TMJ capsule/condyle',
        action:'Medial pterygoid elevates and helps protrude the jaw; lateral pterygoid protrudes and depresses the jaw and drives side-to-side grinding motion.',
        nerve:'CN V3' },
    ]},
    { group: 'Muscles of Facial Expression', muscles: [
      { id:'facial-expression', name:'Facial Expression Muscles (Frontalis, Orbicularis Oculi, Orbicularis Oris, Buccinator, etc.)', origin:'Skull/fascia (varies by muscle)', insertion:'Directly into the skin (unique among skeletal muscles)',
        action:'Produce facial expressions and assist in functions like blinking, closing the lips, and keeping food between the teeth while chewing (buccinator).',
        nerve:'Facial nerve (Cranial Nerve VII)',
        note:'Because they insert into skin rather than bone, damage to CN VII (e.g. Bell\'s palsy) causes visible facial drooping rather than a movement-only deficit.' },
    ]},
  ],
};

// ─── QUIZ (30 MCQ) ───────────────────────────────────────
const ANATOMY_QUIZZES = {
  'upper-limb': {
    title: 'Upper Limb Anatomy Quiz',
    questions: [
      { q:'Which bone is the only bony link between the arm and the axial skeleton?', options:['Scapula','Clavicle','Humerus','Sternum'], correct:1 },
      { q:'The glenoid fossa, which receives the humeral head, is part of which bone?', options:['Clavicle','Humerus','Scapula','Radius'], correct:2 },
      { q:'Which joint is most frequently injured by a fall directly onto the tip of the shoulder?', options:['Sternoclavicular joint','Acromioclavicular joint','Glenohumeral joint','Elbow joint'], correct:1 },
      { q:'Which rotator cuff muscle initiates the first ~15° of shoulder abduction?', options:['Infraspinatus','Subscapularis','Supraspinatus','Teres minor'], correct:2 },
      { q:'Which rotator cuff muscle is the ONLY one located on the anterior (front) surface of the scapula?', options:['Supraspinatus','Subscapularis','Teres minor','Infraspinatus'], correct:1 },
      { q:'Which two rotator cuff muscles are the prime external rotators of the shoulder?', options:['Supraspinatus & subscapularis','Infraspinatus & teres minor','Subscapularis & teres minor','Supraspinatus & infraspinatus'], correct:1 },
      { q:'Weakness of which muscle classically produces a "winged scapula"?', options:['Trapezius','Rhomboids','Serratus anterior','Levator scapulae'], correct:2 },
      { q:'Which muscle is nicknamed the "climbing" muscle for pulling the body up toward a fixed hand (e.g. pull-ups)?', options:['Pectoralis major','Deltoid','Latissimus dorsi','Teres minor'], correct:2 },
      { q:'The lower fibers of which muscle depress the scapula, working with the upper fibers (elevation) and middle fibers (retraction)?', options:['Trapezius','Rhomboids','Serratus anterior','Levator scapulae'], correct:0 },
      { q:'Which humeral landmark is the insertion point for the deltoid?', options:['Greater tubercle','Deltoid tuberosity','Bicipital groove','Lateral epicondyle'], correct:1 },
      { q:'The elbow\'s hinge motion (flexion/extension) primarily occurs at which joint?', options:['Proximal radioulnar joint','Humeroradial joint','Humeroulnar joint','Distal radioulnar joint'], correct:2 },
      { q:'Pronation and supination of the forearm occur mainly at which joint(s)?', options:['Humeroulnar joint','Radioulnar joints','Wrist joint','Elbow (hinge portion)'], correct:1 },
      { q:'Which elbow flexor works effectively regardless of forearm position (pronated or supinated)?', options:['Biceps brachii','Brachioradialis','Brachialis','Supinator'], correct:2 },
      { q:'Which muscle is the primary supinator of the forearm, along with the biceps brachii?', options:['Pronator teres','Supinator','Brachioradialis','Anconeus'], correct:1 },
      { q:'The long head of the biceps brachii originates from which structure?', options:['Coracoid process','Supraglenoid tubercle','Infraglenoid tubercle','Acromion'], correct:1 },
      { q:'Which muscle\'s long head also assists shoulder extension in addition to extending the elbow?', options:['Biceps brachii','Triceps brachii','Brachialis','Brachioradialis'], correct:1 },
      { q:'Pronator teres inserts on which bone?', options:['Ulna','Radius','Humerus','Scaphoid'], correct:1 },
      { q:'Which carpal bone is most commonly fractured after a fall on an outstretched hand, with a notoriously poor healing blood supply?', options:['Lunate','Triquetrum','Scaphoid','Hamate'], correct:2 },
      { q:'How many carpal bones are there in total, in one wrist?', options:['6','7','8','9'], correct:2 },
      { q:'Which of these is in the PROXIMAL row of carpal bones?', options:['Trapezium','Capitate','Lunate','Hamate'], correct:2 },
      { q:'Flexor carpi ulnaris and extensor carpi ulnaris both insert near which bone?', options:['2nd metacarpal','5th metacarpal','Scaphoid','1st metacarpal'], correct:1 },
      { q:'Which muscle flexes the PIP joints of fingers 2–5?', options:['Flexor digitorum superficialis','Extensor digitorum','Lumbricals','Interossei'], correct:0 },
      { q:'The "pen-holding" position — MCP flexion with IP extension — is produced mainly by which muscles?', options:['Interossei','Lumbricals','Thenar group','Extensor digitorum'], correct:1 },
      { q:'Using the "PAD/DAB" rule, which group ADducts the fingers toward the middle finger?', options:['Dorsal interossei','Palmar interossei','Lumbricals','Hypothenar group'], correct:1 },
      { q:'Using the "PAD/DAB" rule, which group ABducts the fingers away from the middle finger?', options:['Palmar interossei','Dorsal interossei','Thenar group','Lumbricals'], correct:1 },
      { q:'The thenar muscle group acts on which digit?', options:['Index finger','Little finger','Thumb','Middle finger'], correct:2 },
      { q:'How many phalanges does the thumb have, compared to a finger?', options:['2 vs 3','3 vs 2','2 vs 2','3 vs 3'], correct:0 },
      { q:'Which forearm bone stays relatively fixed while the other rotates around it during pronation/supination?', options:['Radius','Ulna','Both move equally','Neither moves'], correct:1 },
      { q:'Which is the most mobile joint in the entire body — and, precisely because of that, also the least stable?', options:['Elbow joint','Wrist joint','Glenohumeral joint','Acromioclavicular joint'], correct:2 },
      { q:'Trapezius originates from which region of the spine (in addition to the occiput)?', options:['C1–C7 only','C7–T12','T1–L5','Sacrum'], correct:1 },
      { q:'Which nerve innervates all three anterior/functional heads of the deltoid?', options:['Musculocutaneous nerve','Axillary nerve','Radial nerve','Suprascapular nerve'], correct:1 },
      { q:'Both supraspinatus and infraspinatus share which nerve supply?', options:['Axillary nerve','Suprascapular nerve','Dorsal scapular nerve','Radial nerve'], correct:1 },
      { q:'Which nerve innervates serratus anterior, and whose injury causes a winged scapula?', options:['Dorsal scapular nerve','Long thoracic nerve','Thoracodorsal nerve','Suprascapular nerve'], correct:1 },
      { q:'Triceps brachii is innervated by which nerve?', options:['Musculocutaneous nerve','Median nerve','Radial nerve','Ulnar nerve'], correct:2 },
      { q:'Which nerve innervates biceps brachii?', options:['Radial nerve','Axillary nerve','Musculocutaneous nerve','Median nerve'], correct:2 },
      { q:'Flexor carpi ulnaris is innervated by which nerve?', options:['Median nerve','Ulnar nerve','Radial nerve','Musculocutaneous nerve'], correct:1 },
      { q:'The thenar muscles are innervated by which nerve — making them the classic muscles tested for carpal tunnel syndrome?', options:['Ulnar nerve','Radial nerve','Recurrent branch of the median nerve','Musculocutaneous nerve'], correct:2 },
      { q:'All the interossei of the hand are innervated by which nerve?', options:['Median nerve','Deep branch of the ulnar nerve','Radial nerve','Posterior interosseous nerve'], correct:1 },
      { q:'Which nerve supplies the extensor muscles of the wrist and fingers (via its posterior interosseous branch)?', options:['Median nerve','Ulnar nerve','Radial nerve','Axillary nerve'], correct:2 },
      { q:'Pronator teres is innervated by which nerve?', options:['Radial nerve','Median nerve','Ulnar nerve','Musculocutaneous nerve'], correct:1 },
    ]
  },
  'lower-limb': {
    title: 'Lower Limb Anatomy Quiz',
    questions: [
      { q:'Which bone forms the socket of the hip joint?', options:['Femur','Sacrum','Os coxae (via the acetabulum)','Tibia'], correct:2 },
      { q:'The three bones that fuse to form each os coxae are the ilium, ischium, and which other?', options:['Pubis','Sacrum','Coccyx','Femur'], correct:0 },
      { q:'Which femoral landmark is a common fracture site in osteoporotic falls, often described as a "broken hip"?', options:['Greater trochanter','Femoral neck','Linea aspera','Lateral condyle'], correct:1 },
      { q:'The patella is best classified as what type of bone?', options:['Long bone','Sesamoid bone','Flat bone','Irregular bone'], correct:1 },
      { q:'Which tarsal bone sits directly under the tibia and has no muscle attachments?', options:['Calcaneus','Navicular','Talus','Cuboid'], correct:2 },
      { q:'Which ligament complex is injured in a "high ankle sprain"?', options:['Lateral ankle ligaments','Distal tibiofibular syndesmosis','Deltoid ligament','Plantar fascia'], correct:1 },
      { q:'Which joint produces inversion and eversion of the foot?', options:['Talocrural joint','Subtalar joint','Knee joint','Proximal tibiofibular joint'], correct:1 },
      { q:'Which muscle is the strongest hip flexor?', options:['Sartorius','Tensor fasciae latae','Iliopsoas','Rectus femoris'], correct:2 },
      { q:'Weakness of which muscle classically causes a Trendelenburg (pelvic drop) gait?', options:['Gluteus maximus','Gluteus medius','Piriformis','Adductor magnus'], correct:1 },
      { q:'Which nerve runs beneath (and sometimes through) the piriformis, making tight piriformis a mimic of sciatica?', options:['Femoral nerve','Obturator nerve','Sciatic nerve','Tibial nerve'], correct:2 },
      { q:'Which is the only quadriceps muscle that crosses both the hip and the knee?', options:['Vastus lateralis','Vastus medialis','Vastus intermedius','Rectus femoris'], correct:3 },
      { q:'Which nerve innervates all four heads of the quadriceps?', options:['Obturator nerve','Femoral nerve','Sciatic nerve','Tibial nerve'], correct:1 },
      { q:'Which nerve innervates the adductor group (except part of adductor magnus)?', options:['Femoral nerve','Obturator nerve','Sciatic nerve','Superior gluteal nerve'], correct:1 },
      { q:'Which muscle "unlocks" the fully extended knee to allow flexion to begin?', options:['Popliteus','Gracilis','Sartorius','Gastrocnemius'], correct:0 },
      { q:'Which of these hamstring muscles inserts on the fibula rather than the tibia?', options:['Semitendinosus','Semimembranosus','Biceps femoris','Gracilis'], correct:2 },
      { q:'Which nerve innervates the hamstrings (with one small exception)?', options:['Femoral nerve','Obturator nerve','Tibial division of the sciatic nerve','Deep fibular nerve'], correct:2 },
      { q:'Which muscle dorsiflexes and inverts the foot, and controls the foot\'s lowering after heel strike?', options:['Tibialis anterior','Tibialis posterior','Fibularis longus','Gastrocnemius'], correct:0 },
      { q:'Which two muscles form the calf and insert via the Achilles tendon?', options:['Tibialis anterior & posterior','Gastrocnemius & soleus','Fibularis longus & brevis','Popliteus & plantaris'], correct:1 },
      { q:'Which calf muscle crosses the knee as well as the ankle?', options:['Soleus','Tibialis posterior','Gastrocnemius','Fibularis brevis'], correct:2 },
      { q:'Which muscle group are the primary dynamic stabilizers against ankle-inversion sprains?', options:['Tibialis anterior & posterior','Fibularis (peroneus) longus & brevis','Gastrocnemius & soleus','Extensor digitorum longus & hallucis longus'], correct:1 },
      { q:'Which nerve innervates gastrocnemius and soleus?', options:['Deep fibular nerve','Superficial fibular nerve','Tibial nerve','Femoral nerve'], correct:2 },
      { q:'Which muscle provides the primary dynamic support for the medial longitudinal arch of the foot?', options:['Tibialis anterior','Tibialis posterior','Fibularis longus','Flexor digitorum longus'], correct:1 },
      { q:'How many tarsal bones are there in one foot?', options:['5','6','7','8'], correct:2 },
      { q:'Which nerve supplies most of the intrinsic foot muscles on the sole?', options:['Deep fibular nerve','Medial & lateral plantar nerves (from the tibial nerve)','Superficial fibular nerve','Femoral nerve'], correct:1 },
      { q:'Menisci in the knee joint primarily function to:', options:['Produce rotation','Deepen the tibial plateau & absorb shock','Limit hip motion','Attach the patella to the tibia'], correct:1 },
      { q:'Which structure increases the mechanical advantage (leverage) of the quadriceps?', options:['Meniscus','Patella','Fibula','IT band'], correct:1 },
      { q:'The sacroiliac joint\'s main functional role is:', options:['High mobility for pelvic tilting', 'Load transfer/shock absorption between spine and legs', 'Ankle stability', 'Knee rotation'], correct:1 },
      { q:'Which nerve innervates gluteus maximus?', options:['Superior gluteal nerve','Inferior gluteal nerve','Obturator nerve','Sciatic nerve directly'], correct:1 },
      { q:'Sartorius, the longest muscle in the body, produces which combined hip motion (its classic "tailor\'s pose" action)?', options:['Extension, adduction, internal rotation','Flexion, abduction, external rotation','Flexion, adduction, external rotation','Extension, abduction, internal rotation'], correct:1 },
      { q:'Rectus femoris, semitendinosus, and sartorius all cross which two joints?', options:['Hip and knee','Knee and ankle','Hip and ankle','None cross two joints'], correct:0 },
    ]
  },
  'trunk-spine': {
    title: 'Trunk & Spine Anatomy Quiz',
    questions: [
      { q:'How many vertebrae are in the cervical spine?', options:['5','6','7','8'], correct:2 },
      { q:'Which cervical vertebra is known as the "Atlas"?', options:['C1','C2','C3','C7'], correct:0 },
      { q:'Which cervical vertebra has the dens (odontoid process) that the Atlas pivots around?', options:['C1','C2','C6','C7'], correct:1 },
      { q:'Which spinal region has the LEAST rotation available, mainly due to its near-sagittal facet joint orientation?', options:['Cervical','Thoracic','Lumbar','Sacral'], correct:2 },
      { q:'How many pairs of ribs are classified as "true ribs" (attaching directly to the sternum)?', options:['5','7','10','12'], correct:1 },
      { q:'Ribs 11 and 12 are classified as:', options:['True ribs','False ribs','Floating ribs','Costal ribs'], correct:2 },
      { q:'The sternal angle (between manubrium and body) is a useful landmark for locating which rib?', options:['1st rib','2nd rib','5th rib','7th rib'], correct:1 },
      { q:'Which structure sits between vertebral bodies and can herniate, potentially compressing a nerve root?', options:['Facet joint','Intervertebral disc','Ligamentum flavum','Spinous process'], correct:1 },
      { q:'The nucleus pulposus is surrounded by which structure?', options:['Annulus fibrosus','Facet capsule','Ligamentum flavum','Costal cartilage'], correct:0 },
      { q:'Which joints allow the small gliding motion of the ribs needed for breathing?', options:['Facet joints','Costovertebral & costotransverse joints','Sternocostal joints only','Sacroiliac joints'], correct:1 },
      { q:'Which muscle group are the main extensors of the spine?', options:['Rectus abdominis','Erector spinae','Transversus abdominis','Diaphragm'], correct:1 },
      { q:'Which deep spinal muscle provides segment-by-segment stabilization and is often targeted in low-back-pain rehab?', options:['Quadratus lumborum','Multifidus','External oblique','Latissimus dorsi'], correct:1 },
      { q:'Quadratus lumborum helps with forced exhalation by fixing which structure?', options:['1st rib','12th rib','Sternum','Diaphragm'], correct:1 },
      { q:'Which abdominal muscle rotates the trunk toward the SAME side it contracts on?', options:['External oblique','Internal oblique','Rectus abdominis','Erector spinae'], correct:1 },
      { q:'Which abdominal muscle rotates the trunk toward the OPPOSITE side it contracts on?', options:['Internal oblique','Transversus abdominis','External oblique','Multifidus'], correct:2 },
      { q:'Which is the deepest abdominal muscle, mainly providing core stability rather than producing trunk movement?', options:['Rectus abdominis','External oblique','Internal oblique','Transversus abdominis'], correct:3 },
      { q:'What is the primary muscle of inspiration?', options:['External intercostals','Internal intercostals','Diaphragm','Rectus abdominis'], correct:2 },
      { q:'The diaphragm is innervated by which nerve, and at what spinal levels — per the mnemonic "keeps the diaphragm alive"?', options:['Vagus nerve, C1–C2','Phrenic nerve, C3–C5','Intercostal nerves, T1–T11','Thoracic splanchnic nerve, T5–T9'], correct:1 },
      { q:'Which muscles elevate the ribs to assist inspiration?', options:['Internal intercostals','External intercostals','Transversus abdominis','Quadratus lumborum'], correct:1 },
      { q:'Which muscles assist forced expiration by depressing the ribs?', options:['External intercostals','Internal intercostals','Diaphragm','Erector spinae'], correct:1 },
      { q:'The sacrum is formed by the fusion of how many vertebrae?', options:['3','4','5','6'], correct:2 },
      { q:'Rectus abdominis originates on the pubic crest and inserts on which structures?', options:['Iliac crest','Costal cartilages of ribs 5–7 & xiphoid process','Sacrum','Transverse processes of lumbar vertebrae'], correct:1 },
      { q:'Which spinal region is built with the thickest vertebral bodies to bear the greatest load?', options:['Cervical','Thoracic','Lumbar','Sacral'], correct:2 },
      { q:'Which nerve innervates the intercostal muscles?', options:['Phrenic nerve','Vagus nerve','Intercostal nerves (ventral rami of T1–T11)','Dorsal rami of spinal nerves'], correct:2 },
      { q:'The transverse foramen — a landmark unique to cervical vertebrae — carries which structure?', options:['Spinal cord','Vertebral artery','Esophagus','Trachea'], correct:1 },
      { q:'Erector spinae and multifidus both receive their nerve supply from:', options:['Ventral rami of spinal nerves','Dorsal rami of spinal nerves','The phrenic nerve','Cranial nerves'], correct:1 },
      { q:'Which structure connects the two pubic bones anteriorly?', options:['Pubic symphysis','Sacroiliac joint','Iliac crest','Ischial tuberosity'], correct:0 },
      { q:'The xiphoid process is part of which structure?', options:['Sternum','Rib 12','Sacrum','Costal cartilage of rib 1'], correct:0 },
      { q:'Iliohypogastric and ilioinguinal nerves (L1) contribute to the innervation of which abdominal muscles?', options:['Rectus abdominis only','Internal oblique & transversus abdominis','External oblique only','Erector spinae'], correct:1 },
      { q:'Which spinal curve/region allows the most combined flexion and extension?', options:['Cervical','Thoracic','Lumbar','All are roughly equal'], correct:2 },
    ]
  },
  'head-neck': {
    title: 'Head & Neck Anatomy Quiz',
    questions: [
      { q:'Which cranial bone contains the foramen magnum, where the spinal cord passes through?', options:['Frontal bone','Temporal bone','Occipital bone','Sphenoid bone'], correct:2 },
      { q:'Which bone is the only mobile bone of the skull?', options:['Maxilla','Mandible','Temporal bone','Zygomatic bone'], correct:1 },
      { q:'The mastoid process, an important muscle-attachment landmark, is part of which bone?', options:['Occipital bone','Sphenoid bone','Temporal bone','Frontal bone'], correct:2 },
      { q:'Which small bone in the neck articulates with no other bone, suspended by muscles alone?', options:['Hyoid bone','Mandible','C1 (Atlas)','Sternum'], correct:0 },
      { q:'The atlanto-occipital joint primarily produces which movement?', options:['Head shaking "no"','Head nodding "yes"','Jaw opening','Neck side-bending'], correct:1 },
      { q:'The atlantoaxial joint primarily produces which movement?', options:['Head nodding "yes"','Roughly half of all cervical rotation ("no")','Jaw protrusion','Lateral flexion of the trunk'], correct:1 },
      { q:'The TMJ combines which two types of motion?', options:['Hinge + gliding','Pivot + saddle','Ball-and-socket + hinge','Plane + condyloid'], correct:0 },
      { q:'Which nerve innervates the sternocleidomastoid?', options:['Facial nerve (CN VII)','Accessory nerve (CN XI)','Trigeminal nerve (CN V)','Hypoglossal nerve (CN XII)'], correct:1 },
      { q:'Contracting the sternocleidomastoid on ONE side rotates the head toward which side?', options:['The same side','The opposite side','It doesn\'t rotate the head','Only flexes the neck'], correct:1 },
      { q:'Which muscle group passes between the anterior and middle scalenes, relevant to thoracic outlet syndrome?', options:['Vagus nerve & carotid artery','Brachial plexus & subclavian artery','Phrenic nerve alone','Facial nerve branches'], correct:1 },
      { q:'Which muscles are considered the deep neck flexors, often targeted in cervical stabilization exercises?', options:['Scalenes','Longus colli & longus capitis','Splenius capitis & cervicis','Sternocleidomastoid'], correct:1 },
      { q:'Splenius capitis and cervicis, when contracting on one side, produce which motion?', options:['Contralateral rotation only','Ipsilateral lateral flexion and rotation','Pure flexion','Jaw depression'], correct:1 },
      { q:'The suboccipital muscles are innervated by which nerve?', options:['Facial nerve (CN VII)','Accessory nerve (CN XI)','Suboccipital nerve (dorsal ramus of C1)','Trigeminal nerve (CN V)'], correct:2 },
      { q:'Which nerve innervates all four muscles of mastication (masseter, temporalis, and both pterygoids)?', options:['Facial nerve (CN VII)','Trigeminal nerve, mandibular division (CN V3)','Accessory nerve (CN XI)','Hypoglossal nerve (CN XII)'], correct:1 },
      { q:'Which muscle of mastication is primarily responsible for jaw protrusion and side-to-side grinding?', options:['Masseter','Temporalis','Lateral pterygoid','Medial pterygoid'], correct:2 },
      { q:'Which muscle elevates the jaw and, via its posterior fibers, also retracts the mandible?', options:['Masseter','Temporalis','Lateral pterygoid','Buccinator'], correct:1 },
      { q:'The muscles of facial expression are unusual because they insert into which structure, rather than bone?', options:['Cartilage','Skin','Fascia only','Tendon sheaths'], correct:1 },
      { q:'Which cranial nerve innervates the muscles of facial expression, and whose damage causes visible facial drooping (e.g. Bell\'s palsy)?', options:['CN V (Trigeminal)','CN VII (Facial)','CN XI (Accessory)','CN XII (Hypoglossal)'], correct:1 },
      { q:'Which facial-expression muscle helps keep food between the teeth while chewing?', options:['Frontalis','Orbicularis oculi','Buccinator','Orbicularis oris'], correct:2 },
      { q:'The mandibular fossa, which forms the TMJ socket, is found on which bone?', options:['Mandible','Maxilla','Temporal bone','Sphenoid bone'], correct:2 },
      { q:'Which bone forms most of the roof and sides of the skull, meeting its pair at the sagittal suture?', options:['Frontal bone','Parietal bones','Occipital bone','Temporal bones'], correct:1 },
      { q:'The occipital condyles articulate directly with which vertebra?', options:['C2 (Axis)','C7','C1 (Atlas)','T1'], correct:2 },
      { q:'Which bone forms the upper jaw and much of the hard palate?', options:['Mandible','Maxilla','Zygomatic bone','Vomer'], correct:1 },
      { q:'Cervical facet joints (C3–C7) are oriented at roughly what angle, allowing generous combined motion?', options:['0° (fully horizontal)','45°','90° (fully vertical)','Random, no consistent angle'], correct:1 },
      { q:'Which bone is described as "butterfly-shaped" and articulates with nearly every other cranial bone?', options:['Ethmoid bone','Sphenoid bone','Temporal bone','Occipital bone'], correct:1 },
      { q:'The dens (odontoid process) is a landmark of which vertebra?', options:['C1 (Atlas)','C2 (Axis)','C7','T1'], correct:1 },
      { q:'Scalenes are innervated by which nerve source?', options:['Cranial nerves only','Ventral rami of cervical spinal nerves (C3–C8)','Dorsal rami of cervical spinal nerves','Phrenic nerve only'], correct:1 },
      { q:'Beyond breathing, what secondary action do the scalenes assist with?', options:['Elevating the upper ribs during forced inspiration','Depressing the mandible','Rotating the eyeballs','Extending the thoracic spine'], correct:0 },
      { q:'Which joint type is the TMJ classified as overall?', options:['Simple hinge joint','Compound synovial joint (hinge + gliding, with an articular disc)','Pure ball-and-socket joint','Fibrous joint'], correct:1 },
      { q:'Longus colli and longus capitis are innervated by which nerve roots?', options:['Ventral rami of C1–C6','Dorsal rami of C1–C6','CN XI only','Phrenic nerve'], correct:0 },
    ]
  },
};
