/**
 * anatomy-data.js — ANATOMY module (pilot region: Upper Limb)
 * Text-based study content, written from scratch based on standard
 * musculoskeletal-anatomy knowledge (not copied from any textbook).
 *
 * Structure mirrors a standard PT anatomy curriculum: Bones → Joints → Muscles
 * (grouped, each with Origin / Insertion / Action / Nerve Supply) →
 * 30-question MCQ self-test per region.
 */
'use strict';

const ANATOMY_REGIONS = [
  { id: 'upper-limb', label: 'Upper Limb', sub: 'Shoulder · Elbow · Forearm · Wrist · Hand', icon: '💪', color: '#5A7A62', status: 'ready' },
  { id: 'lower-limb', label: 'Lower Limb', sub: 'Pelvis · Knee · Ankle · Foot', icon: '🦵', color: '#B8943F', status: 'ready' },
  { id: 'trunk-spine', label: 'Trunk & Spine', sub: 'Vertebral column · Thorax', icon: '🧍', color: '#4A6FA5', status: 'ready' },
  { id: 'head-neck', label: 'Head & Neck', sub: 'Skull · Cervical spine · Face', icon: '🧠', color: '#9B59B6', status: 'ready' },
];

// ─── BONES ───────────────────────────────────────────────
const ANATOMY_BONES = {
  'upper-limb': [
    { id:'clavicle', name:'Clavicle', group:'Shoulder Girdle',
      summary:'The collarbone — an S-shaped strut that braces the shoulder out from the sternum.',
      details:'Runs horizontally between the sternum (medial end) and the acromion of the scapula (lateral end). It is one of the most commonly fractured bones (often from a fall onto an outstretched hand or a direct blow to the shoulder), and it is also the first long bone in the body to begin ossifying in the embryo.',
      landmarks:['Sternal (medial) end', 'Acromial (lateral) end', 'Conoid tubercle'] },
    { id:'scapula', name:'Scapula', group:'Shoulder Girdle',
      summary:'The flat, triangular "shoulder blade" that floats over the ribcage, anchored only by muscle.',
      details:'Provides the socket (glenoid fossa) for the humeral head and a broad surface for many shoulder muscles to attach. Its mobility on the rib cage (scapulothoracic motion) is essential for full overhead reach — this is the basis of "scapulohumeral rhythm", where for roughly every 3° of arm elevation about 2° comes from the shoulder joint and 1° from scapular rotation.',
      landmarks:['Glenoid fossa', 'Acromion process', 'Coracoid process', 'Spine of scapula', 'Superior/inferior angle'] },
    { id:'humerus', name:'Humerus', group:'Arm',
      summary:'The single long bone of the upper arm, from shoulder to elbow.',
      details:'Its rounded head sits in the glenoid fossa to form the very mobile (but less stable) glenohumeral joint. Distally it flares into two condyles (capitulum and trochlea) that articulate with the radius and ulna at the elbow. The radial (spiral) groove on its posterior shaft carries the radial nerve — a fracture here is a classic cause of wrist drop.',
      landmarks:['Head', 'Greater & lesser tubercle', 'Deltoid tuberosity', 'Medial/lateral epicondyle', 'Capitulum', 'Trochlea'] },
    { id:'radius', name:'Radius', group:'Forearm',
      summary:'The lateral (thumb-side) forearm bone — it rotates around the ulna to turn the palm up or down.',
      details:'Small proximally (radial head), wide distally, opposite of the ulna. Its rotation at the proximal and distal radioulnar joints produces pronation and supination. A fall onto an outstretched hand classically fractures the distal radius (a "Colles\' fracture").',
      landmarks:['Radial head', 'Radial tuberosity', 'Styloid process'] },
    { id:'ulna', name:'Ulna', group:'Forearm',
      summary:'The medial (pinky-side) forearm bone — large proximally, forms the main elbow hinge.',
      details:'Its olecranon and trochlear notch wrap around the humeral trochlea, giving the elbow its stable hinge motion. It stays relatively fixed while the radius rotates around it.',
      landmarks:['Olecranon process', 'Trochlear notch', 'Coronoid process', 'Styloid process'] },
    { id:'carpals', name:'Carpal Bones (×8)', group:'Wrist',
      summary:'Two rows of four small bones that make up the wrist.',
      details:'Proximal row: Scaphoid, Lunate, Triquetrum, Pisiform. Distal row: Trapezium, Trapezoid, Capitate, Hamate. The scaphoid is the most frequently fractured carpal bone (classic "fall on outstretched hand" injury) and is prone to non-union/avascular necrosis because its blood supply enters distally and runs backward through the bone. A common memory aid for the 8 carpals (proximal → distal, lateral → medial) is "Some Lovers Try Positions That They Can\'t Handle".',
      landmarks:['Scaphoid', 'Lunate', 'Triquetrum', 'Pisiform', 'Trapezium', 'Trapezoid', 'Capitate', 'Hamate'] },
    { id:'metacarpals', name:'Metacarpals (×5)', group:'Hand',
      summary:'The five bones forming the palm, one per finger/thumb ray.',
      details:'Numbered 1 (thumb) to 5 (little finger). Their heads form the knuckles (MCP joints).',
      landmarks:['Base', 'Shaft', 'Head'] },
    { id:'phalanges', name:'Phalanges', group:'Hand',
      summary:'The finger and thumb bones — 14 in total per hand.',
      details:'The thumb has 2 (proximal, distal); each finger has 3 (proximal, middle, distal).',
      landmarks:['Proximal phalanx', 'Middle phalanx', 'Distal phalanx'] },
  ]
};

// ─── JOINTS ──────────────────────────────────────────────
const ANATOMY_JOINTS = {
  'upper-limb': [
    { id:'sternoclavicular', name:'Sternoclavicular (SC) Joint', type:'Saddle',
      summary:'The only bony connection between the arm and the axial skeleton.',
      extra:'Despite carrying the entire load of the upper limb through it, this small joint is stabilized mainly by strong ligaments (costoclavicular, interclavicular) rather than bone shape.' },
    { id:'acromioclavicular', name:'Acromioclavicular (AC) Joint', type:'Plane/gliding',
      summary:'Where the clavicle meets the acromion; a common site of "separated shoulder" injuries from a fall onto the shoulder tip.',
      extra:'AC separations are graded I–VI based on how many of the AC and coracoclavicular ligaments are torn.' },
    { id:'glenohumeral', name:'Glenohumeral (GH) Joint', type:'Ball and socket',
      summary:'The main shoulder joint — the most mobile joint in the body, which is exactly why it is also the least stable and most frequently dislocated.',
      extra:'The glenoid fossa is shallow and only covers about a third of the humeral head — often compared to "a golf ball sitting on a tee". Stability relies heavily on the rotator cuff and the labrum (a fibrocartilage rim).' },
    { id:'elbow-complex', name:'Elbow Joint Complex', type:'Hinge (humeroulnar) + pivot (humeroradial)',
      summary:'Functions as a hinge for flexion/extension while the radial head also rotates for pronation/supination.',
      extra:'All three elbow articulations (humeroulnar, humeroradial, proximal radioulnar) share one joint capsule.' },
    { id:'radioulnar', name:'Radioulnar Joints (proximal + distal)', type:'Pivot',
      summary:'Working together, these two joints let the radius rotate around the ulna to pronate/supinate the forearm.',
      extra:'The interosseous membrane connecting the radius and ulna also helps transmit force from the hand up to the elbow.' },
    { id:'wrist', name:'Wrist (Radiocarpal) Joint', type:'Condyloid',
      summary:'Between the distal radius and the proximal carpal row; allows flexion, extension, radial/ulnar deviation.' },
    { id:'hand-joints', name:'Hand Joints (CMC, MCP, IP)', type:'Saddle / condyloid / hinge',
      summary:'CMC joints (base of fingers) mostly glide; MCP knuckles allow flexion + some ab/adduction; IP joints are pure hinges.',
      extra:'The thumb\'s CMC joint is the exception — its true saddle shape gives it the extra freedom needed for opposition.' },
  ]
};

// ─── MUSCLES (grouped) ───────────────────────────────────
const ANATOMY_MUSCLE_GROUPS = {
  'upper-limb': [
    { group: 'Superficial Shoulder Movers', muscles: [
      { id:'deltoid', name:'Deltoid', origin:'Lateral 1/3 of clavicle, acromion, spine of scapula', insertion:'Deltoid tuberosity of humerus',
        action:'Anterior fibers flex/internally rotate; middle fibers abduct; posterior fibers extend/externally rotate the shoulder.',
        nerve:'Axillary nerve (C5–C6)',
        note:'The main prime mover for shoulder abduction after the first ~15° (which supraspinatus initiates).' },
      { id:'pec-major', name:'Pectoralis Major', origin:'Clavicle, sternum, upper costal cartilages', insertion:'Lateral lip of bicipital groove (humerus)',
        action:'Flexes, adducts, and internally rotates the shoulder.',
        nerve:'Medial & lateral pectoral nerves (C5–T1)',
        note:'Big, powerful "pushing" muscle — think push-ups and bench press.' },
      { id:'lat-dorsi', name:'Latissimus Dorsi', origin:'Lower thoracic/lumbar spine, iliac crest, lower ribs', insertion:'Floor of bicipital groove (humerus)',
        action:'Extends, adducts, and internally rotates the shoulder.',
        nerve:'Thoracodorsal nerve (C6–C8)',
        note:'The "climbing" muscle — pulling the body up toward a fixed arm (pull-ups).' },
      { id:'trapezius', name:'Trapezius', origin:'Occiput, spinous processes C7–T12', insertion:'Clavicle, acromion, spine of scapula',
        action:'Upper fibers elevate; middle fibers retract; lower fibers depress the scapula — together they upwardly rotate it for overhead reach.',
        nerve:'Accessory nerve (Cranial Nerve XI), with sensory/proprioceptive fibers from C3–C4',
        note:'Often overworked/tight in people who sit at a desk all day.' },
      { id:'teres-major', name:'Teres Major', origin:'Inferior angle of scapula', insertion:'Medial lip of bicipital groove (humerus)',
        action:'Extends, adducts, internally rotates the shoulder.',
        nerve:'Lower subscapular nerve (C5–C7)',
        note:"Nicknamed \"lat's little helper\" for sharing latissimus dorsi's action." },
    ]},
    { group: 'Rotator Cuff (Deep Stabilizers)', muscles: [
      { id:'supraspinatus', name:'Supraspinatus', origin:'Supraspinous fossa of scapula', insertion:'Greater tubercle of humerus',
        action:'Initiates the first ~15° of shoulder abduction and stabilizes the humeral head in the glenoid.',
        nerve:'Suprascapular nerve (C5–C6)',
        note:'The most commonly injured rotator-cuff muscle/tendon.' },
      { id:'infraspinatus', name:'Infraspinatus', origin:'Infraspinous fossa of scapula', insertion:'Greater tubercle of humerus',
        action:'Externally rotates the shoulder; stabilizes the humeral head.',
        nerve:'Suprascapular nerve (C5–C6)' },
      { id:'teres-minor', name:'Teres Minor', origin:'Lateral border of scapula', insertion:'Greater tubercle of humerus',
        action:'Externally rotates the shoulder; stabilizes the humeral head.',
        nerve:'Axillary nerve (C5–C6)' },
      { id:'subscapularis', name:'Subscapularis', origin:'Subscapular fossa (anterior scapula)', insertion:'Lesser tubercle of humerus',
        action:'Internally rotates the shoulder; stabilizes the humeral head (the only rotator-cuff muscle on the front of the scapula).',
        nerve:'Upper & lower subscapular nerves (C5–C7)',
        note:'Easy memory aid for the 4 rotator cuff muscles: "SItS" — Supraspinatus, Infraspinatus, teres minor, Subscapularis.' },
    ]},
    { group: 'Scapular Stabilizers', muscles: [
      { id:'rhomboids', name:'Rhomboids (Major & Minor)', origin:'Spinous processes C7–T5', insertion:'Medial border of scapula',
        action:'Retract and downwardly rotate the scapula; hold the scapula against the rib cage.',
        nerve:'Dorsal scapular nerve (C4–C5)' },
      { id:'levator-scap', name:'Levator Scapulae', origin:'Transverse processes C1–C4', insertion:'Superior angle of scapula',
        action:'Elevates the scapula; helps rotate the neck.',
        nerve:'Dorsal scapular nerve and direct branches of C3–C4',
        note:'Common source of "stiff neck" tightness.' },
      { id:'serratus-ant', name:'Serratus Anterior', origin:'Ribs 1–8/9 (lateral surface)', insertion:'Medial border of scapula (anterior surface)',
        action:'Protracts the scapula and rotates it upward — essential for full overhead pushing/punching motions.',
        nerve:'Long thoracic nerve (C5–C7)',
        note:'Weakness (e.g. from long thoracic nerve injury) causes a "winged scapula".' },
    ]},
    { group: 'Elbow & Forearm Movers', muscles: [
      { id:'biceps-brachii', name:'Biceps Brachii', origin:'Long head: supraglenoid tubercle; Short head: coracoid process', insertion:'Radial tuberosity',
        action:'Flexes the elbow and supinates the forearm; assists shoulder flexion.',
        nerve:'Musculocutaneous nerve (C5–C6)' },
      { id:'triceps-brachii', name:'Triceps Brachii', origin:'Long head: infraglenoid tubercle; Lateral & medial heads: posterior humerus', insertion:'Olecranon process of ulna',
        action:'Extends the elbow; the long head also assists shoulder extension.',
        nerve:'Radial nerve (C6–C8)' },
      { id:'brachialis', name:'Brachialis', origin:'Distal anterior humerus', insertion:'Coronoid process of ulna',
        action:'Pure elbow flexor — works regardless of forearm position (unlike biceps).',
        nerve:'Musculocutaneous nerve, with a small contribution from the radial nerve (C5–C6)' },
      { id:'brachioradialis', name:'Brachioradialis', origin:'Lateral supracondylar ridge of humerus', insertion:'Styloid process of radius',
        action:'Flexes the elbow; strongest when the forearm is in mid-pronation ("hammer curl" muscle).',
        nerve:'Radial nerve (C5–C6)',
        note:'Unusual for being a forearm muscle innervated by the radial nerve yet acting purely as a flexor.' },
      { id:'pronator-teres', name:'Pronator Teres', origin:'Medial epicondyle of humerus, coronoid process of ulna', insertion:'Lateral surface of radius',
        action:'Pronates the forearm (turns palm down); assists elbow flexion.',
        nerve:'Median nerve (C6–C7)' },
      { id:'supinator', name:'Supinator', origin:'Lateral epicondyle of humerus, proximal ulna', insertion:'Proximal lateral radius',
        action:'Supinates the forearm (turns palm up).',
        nerve:'Deep branch of the radial nerve / posterior interosseous nerve (C5–C6)' },
    ]},
    { group: 'Wrist & Finger Movers (Extrinsic)', muscles: [
      { id:'fcr', name:'Flexor Carpi Radialis', origin:'Medial epicondyle of humerus', insertion:'Base of 2nd/3rd metacarpal',
        action:'Flexes and radially deviates the wrist.',
        nerve:'Median nerve (C6–C7)' },
      { id:'fcu', name:'Flexor Carpi Ulnaris', origin:'Medial epicondyle, olecranon', insertion:'Pisiform, hamate, 5th metacarpal',
        action:'Flexes and ulnarly deviates the wrist.',
        nerve:'Ulnar nerve (C7–T1)' },
      { id:'fds', name:'Flexor Digitorum Superficialis', origin:'Medial epicondyle, radius', insertion:'Middle phalanges of fingers 2–5',
        action:'Flexes the PIP joints (and assists MCP/wrist flexion).',
        nerve:'Median nerve (C7–T1)' },
      { id:'ecrl-b', name:'Extensor Carpi Radialis Longus & Brevis', origin:'Lateral supracondylar ridge / lateral epicondyle', insertion:'Base of 2nd/3rd metacarpal',
        action:'Extend and radially deviate the wrist.',
        nerve:'Radialis longus: radial nerve; Radialis brevis: posterior interosseous nerve (C5–C7)' },
      { id:'ecu', name:'Extensor Carpi Ulnaris', origin:'Lateral epicondyle, ulna', insertion:'Base of 5th metacarpal',
        action:'Extends and ulnarly deviates the wrist.',
        nerve:'Posterior interosseous nerve, a branch of the radial nerve (C7–C8)' },
      { id:'ed', name:'Extensor Digitorum', origin:'Lateral epicondyle of humerus', insertion:'Extensor expansions of fingers 2–5',
        action:'Extends the fingers and assists wrist extension.',
        nerve:'Posterior interosseous nerve, a branch of the radial nerve (C7–C8)' },
    ]},
    { group: 'Intrinsic Hand Muscles', muscles: [
      { id:'thenar', name:'Thenar Group (Abd./Flex./Opponens Pollicis Brevis)', origin:'Flexor retinaculum, carpal bones', insertion:'Base of thumb (1st metacarpal/proximal phalanx)',
        action:'Abduct, flex, and oppose the thumb — the base of the thumb pad.',
        nerve:'Recurrent (motor) branch of the median nerve',
        note:'This nerve branch runs very superficially, which is why the thenar eminence is the classic muscle group tested for carpal tunnel syndrome.' },
      { id:'hypothenar', name:'Hypothenar Group (Abd./Flex./Opponens Digiti Minimi)', origin:'Flexor retinaculum, hamate', insertion:'Base of little finger (5th metacarpal/proximal phalanx)',
        action:'Abduct, flex, and oppose the little finger — the base of the pinky pad.',
        nerve:'Deep branch of the ulnar nerve' },
      { id:'lumbricals', name:'Lumbricals', origin:'Tendons of flexor digitorum profundus', insertion:'Extensor expansions of fingers',
        action:'Flex the MCP joints while extending the IP joints — the classic "pen-holding" position.',
        nerve:'Lumbricals 1–2 (index/middle): median nerve; Lumbricals 3–4 (ring/little): deep branch of ulnar nerve' },
      { id:'interossei', name:'Interossei (Palmar & Dorsal)', origin:'Shafts of metacarpals', insertion:'Base of proximal phalanges / extensor expansions',
        action:'Palmar interossei ADduct the fingers; dorsal interossei ABduct the fingers ("PAD/DAB" rule). Both assist lumbricals at the MCP/IP joints.',
        nerve:'Deep branch of the ulnar nerve' },
    ]},
  ]
};

// ─── QUIZ (30 MCQ) ───────────────────────────────────────
const ANATOMY_QUIZZES = {
  'upper-limb': {
    title: 'Upper Limb Anatomy Quiz',
    questions: [
      { q:'Which bone is the only bony link between the arm and the axial skeleton?', options:['Scapula','Clavicle','Humerus','Sternum'], correct:1 },
      { q:'The glenoid fossa, which receives the humeral head, is part of which bone?', options:['Clavicle','Humerus','Scapula','Radius'], correct:2 },
      { q:'Which joint is most frequently injured by a fall directly onto the tip of the shoulder?', options:['Sternoclavicular joint','Acromioclavicular joint','Glenohumeral joint','Elbow joint'], correct:1 },
      { q:'Which rotator cuff muscle initiates the first ~15° of shoulder abduction?', options:['Infraspinatus','Subscapularis','Supraspinatus','Teres minor'], correct:2 },
      { q:'Which rotator cuff muscle is the ONLY one located on the anterior (front) surface of the scapula?', options:['Supraspinatus','Subscapularis','Teres minor','Infraspinatus'], correct:1 },
      { q:'Which two rotator cuff muscles are the prime external rotators of the shoulder?', options:['Supraspinatus & subscapularis','Infraspinatus & teres minor','Subscapularis & teres minor','Supraspinatus & infraspinatus'], correct:1 },
      { q:'Weakness of which muscle classically produces a "winged scapula"?', options:['Trapezius','Rhomboids','Serratus anterior','Levator scapulae'], correct:2 },
      { q:'Which muscle is nicknamed the "climbing" muscle for pulling the body up toward a fixed hand (e.g. pull-ups)?', options:['Pectoralis major','Deltoid','Latissimus dorsi','Teres minor'], correct:2 },
      { q:'The lower fibers of which muscle depress the scapula, working with the upper fibers (elevation) and middle fibers (retraction)?', options:['Trapezius','Rhomboids','Serratus anterior','Levator scapulae'], correct:0 },
      { q:'Which humeral landmark is the insertion point for the deltoid?', options:['Greater tubercle','Deltoid tuberosity','Bicipital groove','Lateral epicondyle'], correct:1 },
      { q:'The elbow\'s hinge motion (flexion/extension) primarily occurs at which joint?', options:['Proximal radioulnar joint','Humeroradial joint','Humeroulnar joint','Distal radioulnar joint'], correct:2 },
      { q:'Pronation and supination of the forearm occur mainly at which joint(s)?', options:['Humeroulnar joint','Radioulnar joints','Wrist joint','Elbow (hinge portion)'], correct:1 },
      { q:'Which elbow flexor works effectively regardless of forearm position (pronated or supinated)?', options:['Biceps brachii','Brachioradialis','Brachialis','Supinator'], correct:2 },
      { q:'Which muscle is the primary supinator of the forearm, along with the biceps brachii?', options:['Pronator teres','Supinator','Brachioradialis','Anconeus'], correct:1 },
      { q:'The long head of the biceps brachii originates from which structure?', options:['Coracoid process','Supraglenoid tubercle','Infraglenoid tubercle','Acromion'], correct:1 },
      { q:'Which muscle\'s long head also assists shoulder extension in addition to extending the elbow?', options:['Biceps brachii','Triceps brachii','Brachialis','Brachioradialis'], correct:1 },
      { q:'Pronator teres inserts on which bone?', options:['Ulna','Radius','Humerus','Scaphoid'], correct:1 },
      { q:'Which carpal bone is most commonly fractured after a fall on an outstretched hand, with a notoriously poor healing blood supply?', options:['Lunate','Triquetrum','Scaphoid','Hamate'], correct:2 },
      { q:'How many carpal bones are there in total, in one wrist?', options:['6','7','8','9'], correct:2 },
      { q:'Which of these is in the PROXIMAL row of carpal bones?', options:['Trapezium','Capitate','Lunate','Hamate'], correct:2 },
      { q:'Flexor carpi ulnaris and extensor carpi ulnaris both insert near which bone?', options:['2nd metacarpal','5th metacarpal','Scaphoid','1st metacarpal'], correct:1 },
      { q:'Which muscle flexes the PIP joints of fingers 2–5?', options:['Flexor digitorum superficialis','Extensor digitorum','Lumbricals','Interossei'], correct:0 },
      { q:'The "pen-holding" position — MCP flexion with IP extension — is produced mainly by which muscles?', options:['Interossei','Lumbricals','Thenar group','Extensor digitorum'], correct:1 },
      { q:'Using the "PAD/DAB" rule, which group ADducts the fingers toward the middle finger?', options:['Dorsal interossei','Palmar interossei','Lumbricals','Hypothenar group'], correct:1 },
      { q:'Using the "PAD/DAB" rule, which group ABducts the fingers away from the middle finger?', options:['Palmar interossei','Dorsal interossei','Thenar group','Lumbricals'], correct:1 },
      { q:'The thenar muscle group acts on which digit?', options:['Index finger','Little finger','Thumb','Middle finger'], correct:2 },
      { q:'How many phalanges does the thumb have, compared to a finger?', options:['2 vs 3','3 vs 2','2 vs 2','3 vs 3'], correct:0 },
      { q:'Which forearm bone stays relatively fixed while the other rotates around it during pronation/supination?', options:['Radius','Ulna','Both move equally','Neither moves'], correct:1 },
      { q:'Which is the most mobile joint in the entire body — and, precisely because of that, also the least stable?', options:['Elbow joint','Wrist joint','Glenohumeral joint','Acromioclavicular joint'], correct:2 },
      { q:'Trapezius originates from which region of the spine (in addition to the occiput)?', options:['C1–C7 only','C7–T12','T1–L5','Sacrum'], correct:1 },
      { q:'Which nerve innervates all three anterior/functional heads of the deltoid?', options:['Musculocutaneous nerve','Axillary nerve','Radial nerve','Suprascapular nerve'], correct:1 },
      { q:'Both supraspinatus and infraspinatus share which nerve supply?', options:['Axillary nerve','Suprascapular nerve','Dorsal scapular nerve','Radial nerve'], correct:1 },
      { q:'Which nerve innervates serratus anterior, and whose injury causes a winged scapula?', options:['Dorsal scapular nerve','Long thoracic nerve','Thoracodorsal nerve','Suprascapular nerve'], correct:1 },
      { q:'Triceps brachii is innervated by which nerve?', options:['Musculocutaneous nerve','Median nerve','Radial nerve','Ulnar nerve'], correct:2 },
      { q:'Which nerve innervates biceps brachii?', options:['Radial nerve','Axillary nerve','Musculocutaneous nerve','Median nerve'], correct:2 },
      { q:'Flexor carpi ulnaris is innervated by which nerve?', options:['Median nerve','Ulnar nerve','Radial nerve','Musculocutaneous nerve'], correct:1 },
      { q:'The thenar muscles are innervated by which nerve — making them the classic muscles tested for carpal tunnel syndrome?', options:['Ulnar nerve','Radial nerve','Recurrent branch of the median nerve','Musculocutaneous nerve'], correct:2 },
      { q:'All the interossei of the hand are innervated by which nerve?', options:['Median nerve','Deep branch of the ulnar nerve','Radial nerve','Posterior interosseous nerve'], correct:1 },
      { q:'Which nerve supplies the extensor muscles of the wrist and fingers (via its posterior interosseous branch)?', options:['Median nerve','Ulnar nerve','Radial nerve','Axillary nerve'], correct:2 },
      { q:'Pronator teres is innervated by which nerve?', options:['Radial nerve','Median nerve','Ulnar nerve','Musculocutaneous nerve'], correct:1 },
    ]
  }
};
